---
- hosts: raspberries
  tasks:
    - name: Collect sensor data
      shell: "python ~/sensor/main.py"

    - name: Collect IP address
      shell: "ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1 > ~/sensor_data/ip"

    - name: Send data
      shell: "bash ~/STEM-SLAM/raspberry_files/send_data.sh"